### PR TITLE
change /login url to /omk/login

### PR DESCRIPTION
**Pull request by willemarcel**
Solves https://github.com/hotosm/OpenMapKitServer/issues/35

### CODE REVIEW

**Comment by mojodna** [comment]
This should be relative. When standalone it'll be on `/login`, but in some circumstances it will have a prefix (which may be `/omk`, but not necessarily).

**Comment by willemarcel** [comment]
@mojodna would you mind reviewing it again, please?

**Comment by mojodna** [comment]
Looks great; I'm assuming that this works in development, yeah?

**Comment by mojodna** [comment]
This still doesn't work when mounted under `/omk`.

**Comment by mojodna** [comment]
2 reasons:

1) `login` is relative to `/omk/pages/#/login`, so it's effectively `/omk/pages/login`
2) `frontend/build` has been checked in and is out of date.

Here's a diff to `Dockerfile` that rebuilds the frontend as part of packaging up the whole app (this doesn't address non-Docker execution though):

```diff
diff --git a/Dockerfile b/Dockerfile
index 13bd256..bbe0a75 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -44,6 +44,10 @@ RUN \

 COPY . /app/

+RUN \
+  cd frontend && yarn \
+  && yarn build
+
 RUN \
   git submodule update --init \
   && useradd omkserver -m \
```

**Comment by mojodna** [comment]
I'm sorry. I misunderstood part of how this was deployed; it's not actually "mounted on `/omk`", it's that **only** `/omk` routes are proxied through to the API (with a couple of exceptions to support ODK, e.g. `/formList`). This is why `/` redirects to `/omk/pages/`. All of my nonsense about "relative" routing wasn't helpful.

New routes under `/` won't be accessible when running under a proxy configuration like this, so the original commit in this PR is correct.

Proposed fix: 

1. revert 1273304
2. apply `current-user` patch (below) to allow the frontend to request the current user under ^^ proxied environments
3. apply the `Dockerfile` patch (previous comment)
4. rebuild + commit `frontend/build` (or remove + `gitignore` it from the repo)

`current-user` patch:

```diff
diff --cc frontend/src/network/auth.js
index 3574231,3168922..0000000
--- a/frontend/src/network/auth.js
+++ b/frontend/src/network/auth.js
@@@ -1,5 -1,5 +1,5 @@@
  export function currentUser(): Promise<*> {
-   return fetch(`/current-user`, {
 -  return fetch(`../current-user`, {
++  return fetch(`/omk/current-user`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json'
diff --cc frontend/src/store/actions/auth.js
index d17fec0,f9e2ffa..0000000
--- a/frontend/src/store/actions/auth.js
+++ b/frontend/src/store/actions/auth.js
diff --git a/index.js b/index.js
index 7d3ec80..496ae28 100644
--- a/index.js
+++ b/index.js
@@ -111,7 +111,7 @@ app.get('/', redirectToForms);
 app.get('/omk', redirectToForms);
 app.get('/omk/info', info);

-app.get('/current-user',
+app.get('/omk/current-user',
   function(req, res) {
     if (req.user) {
       res.json({ username: req.user.username, role: req.user.role});
```

**Comment by willemarcel** [comment]
Replaced it by https://github.com/hotosm/OpenMapKitServer/pull/42

I didn't change the `/current-user`, because it is not being used by the frontend and it was replaced by `/omk/auth-status/` on https://github.com/hotosm/OpenMapKitServer/pull/41

**Pull request closed without merging**
